language:
- cpp
compiler:
- g++
before_install:
- sudo apt-get update
- sudo apt-get install -y libsnappy-dev
- sudo apt-get install -y zlib1g-dev
- sudo apt-get install -y libbz2-dev
before_script:
- cd rocksdb-4.4
- make install
script:
- cd tallerII/AppServer
- make

