language:
- cpp
compiler:
- g++
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- test -n $CC  && unset CC
- test -n $CXX && unset CXX
- sudo apt-get update
- sudo apt-get install -qq g++-4.8
- sudo apt-get install -y libsnappy-dev
- sudo apt-get install -y zlib1g-dev
- sudo apt-get install -y libbz2-dev
before_script:
- sudo chmod -R 777 rocksdb-4.4
- cd rocksdb-4.4
- sudo make install
script:
- cd tallerII/AppServer
- sudo make

