language: c
compiler:
  - gcc
before_install:
  - sudo pip install codecov
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libjansson-dev check libssl-dev lcov curl
script:
  - autoreconf -i && ./configure --enable-gcov && make coverage
after_success:
  - codecov
